### ISSUE TITLE
tmp dir must exist

### ISSUE THREAD

**Issue by CarolineOhrman** [FOI-Bioinformatics/CanSNPer2#1]
Mauve could not run if tmp dir was nonexistent
```
Traceback (most recent call last):
  File "/data/users/carodl/miniconda3/envs/cansnper2/bin/CanSNPer2", line 11, in <module>
    load_entry_point('CanSNPer2==2.0.1', 'console_scripts', 'CanSNPer2')()
  File "/data/users/carodl/miniconda3/envs/cansnper2/lib/python3.8/site-packages/pkg_resources/__init__.py", line 490, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/data/users/carodl/miniconda3/envs/cansnper2/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2854, in load_entry_point
    return ep.load()
  File "/data/users/carodl/miniconda3/envs/cansnper2/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2445, in load
    return self.resolve()
  File "/data/users/carodl/miniconda3/envs/cansnper2/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2451, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/data/users/carodl/miniconda3/envs/cansnper2/lib/python3.8/site-packages/CanSNPer2-2.0.1-py3.8.egg/CanSNPer2/CanSNPerTree.py", line 41, in <module>
    from CanSNPer2.modules.CanSNPer2 import CanSNPer2
  File "/data/users/carodl/miniconda3/envs/cansnper2/lib/python3.8/site-packages/CanSNPer2-2.0.1-py3.8.egg/CanSNPer2/modules/CanSNPer2.py", line 22, in <module>
    from CanSNPer2.modules.NewickTree import NewickTree
  File "/data/users/carodl/miniconda3/envs/cansnper2/lib/python3.8/site-packages/CanSNPer2-2.0.1-py3.8.egg/CanSNPer2/modules/NewickTree.py", line 7, in <module>
    from flextaxd.modules.database.DatabaseConnection import DatabaseFunctions
ModuleNotFoundError: No module named 'flextaxd'
```

**Comment by CarolineOhrman** [comment]
Tested and working. it was a permission error in the default /tmp/CanSNPer dir.
