### ISSUE TITLE
Installation issues

### ISSUE THREAD

**Issue by druvus** [FOI-Bioinformatics/CanSNPer2#19]
xref from CanSNPer1: adrlar/CanSNPer#28 were @standage mention the following issue with installing CanSNPer2. 

I was able to install CanSNPer2 in a new Conda environment, and download the Ft database. But unfortunately I get the following error when I run it on an Ft sample.

<pre>$ CanSNPer2 --database francisella_tularensis.db Ft.fna                                              
Run 1 alignments to references using progressiveMauve
Traceback (most recent call last):
  File "/home/standage/anaconda3/envs/cansnper2/lib/python3.7/site-packages/CanSNPer2/modules/CanSNPer2.py", line 379, in run
    final_snp,message,called = self.create_tree(SNPS,self.query_name,called_snps,self.save_tree,min_required_hits=self.min_required_hits,strictness=self.strictness)
  File "/home/standage/anaconda3/envs/cansnper2/lib/python3.7/site-packages/CanSNPer2/modules/CanSNPer2.py", line 218, in create_tree
    final_snp = newickTree.draw_ete3_tree(SNPS,called_snps,save_tree,summary=summary)
  File "/home/standage/anaconda3/envs/cansnper2/lib/python3.7/site-packages/CanSNPer2/modules/NewickTree.py", line 288, in draw_ete3_tree
    nstyle = ete3.NodeStyle()
AttributeError: module 'ete3' has no attribute 'NodeStyle'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/standage/anaconda3/envs/cansnper2/bin/CanSNPer2", line 10, in <module>
    sys.exit(main())
  File "/home/standage/anaconda3/envs/cansnper2/lib/python3.7/site-packages/CanSNPer2/CanSNPerTree.py", line 164, in main
    CanSNPer2_obj.run(database=args.database)
  File "/home/standage/anaconda3/envs/cansnper2/lib/python3.7/site-packages/CanSNPer2/modules/CanSNPer2.py", line 407, in run
    raise CanSNPer2Error("A file did not run correctly exit CanSNPer2 (use --keep_going to continue with next file!)")
CanSNPer2.modules.CanSNPer2.CanSNPer2Error: 'A file did not run correctly exit CanSNPer2 (use --keep_going to continue with next file!)'
</pre>

**Comment by druvus** [comment]
Could you give some information about your operating system? 

Could you also paste the conda channel order and conda version? You may get that information by the command  `conda info`

**Comment by davve2** [comment]
Change back to import each function 

from ete3 import Tree, faces, AttrFace, TreeStyle, NodeStyle

and instead fix so that conda installation (won´t crashing on importing faces).
Related to this issue (https://github.com/etetoolkit/ete/issues/315
). Requires pyqt (5 or later) to be installed.

**Comment by CarolineOhrman** [comment]
@standage I tested the same command as you with the public FSC200 genome and it worked fine

` CanSNPer2 --database ~/github/CanSNPer2-data/database/francisella_tularensis.db fasta/FSC200_GCF000168775.2.fna`

This is whats in my conda environment. (`conda list`) Running conda 4.8.2

```
# packages in environment at /mnt/powervault/carodl/miniconda3/envs/cansnper2_conda:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                      1_llvm    conda-forge
ca-certificates           2020.4.5.1           hecc5488_0    conda-forge
cansnper2                 2.0.6                      py_0    bioconda
certifi                   2020.4.5.1       py38h32f6830_0    conda-forge
dbus                      1.13.6               he372182_0    conda-forge
ete3                      3.1.1                      py_1    conda-forge
expat                     2.2.9                he1b5a44_2    conda-forge
flextaxd                  0.2.1                      py_0    bioconda
fontconfig                2.13.1            h86ecdb6_1001    conda-forge
freetype                  2.10.1               he06d7ca_0    conda-forge
gettext                   0.19.8.1          hc5be6a0_1002    conda-forge
glib                      2.64.2               h6f030ca_0    conda-forge
gst-plugins-base          1.14.5               h0935bb2_2    conda-forge
gstreamer                 1.14.5               h36ae1b5_2    conda-forge
icu                       64.2                 he1b5a44_1    conda-forge
jpeg                      9c                h14c3975_1001    conda-forge
ld_impl_linux-64          2.34                 h53a641e_0    conda-forge
libblas                   3.8.0               16_openblas    conda-forge
libcblas                  3.8.0               16_openblas    conda-forge
libclang                  9.0.1           default_hde54327_0    conda-forge
libffi                    3.2.1             he1b5a44_1007    conda-forge
libgcc-ng                 9.2.0                h24d8f2e_2    conda-forge
libgfortran-ng            7.3.0                hdf63c60_5    conda-forge
libiconv                  1.15              h516909a_1006    conda-forge
liblapack                 3.8.0               16_openblas    conda-forge
libllvm9                  9.0.1                he513fc3_1    conda-forge
libopenblas               0.3.9                h5ec1e0e_0    conda-forge
libpng                    1.6.37               hed695b0_1    conda-forge
libstdcxx-ng              9.2.0                hdf63c60_2    conda-forge
libuuid                   2.32.1            h14c3975_1000    conda-forge
libxcb                    1.13              h14c3975_1002    conda-forge
libxkbcommon              0.10.0               he1b5a44_0    conda-forge
libxml2                   2.9.10               hee79883_0    conda-forge
libxslt                   1.1.33               h31b3aaa_0    conda-forge
llvm-openmp               10.0.0               hc9558a2_0    conda-forge
lxml                      4.5.0            py38hbb43d70_1    conda-forge
ncurses                   6.1               hf484d3e_1002    conda-forge
nspr                      4.25                 he1b5a44_0    conda-forge
nss                       3.47                 he751ad9_0    conda-forge
numpy                     1.18.4           py38h8854b6b_0    conda-forge
openssl                   1.1.1g               h516909a_0    conda-forge
pcre                      8.44                 he1b5a44_0    conda-forge
pip                       20.1               pyh9f0ad1d_0    conda-forge
progressivemauve          snapshot_2015_02_13               2    bioconda
pthread-stubs             0.4               h14c3975_1001    conda-forge
pyqt                      5.12.3           py38ha8c2ead_2    conda-forge
pyqt5-sip                 4.19.18                  pypi_0    pypi
pyqtchart                 5.12                     pypi_0    pypi
pyqtwebengine             5.12.1                   pypi_0    pypi
python                    3.8.2           he5300dc_7_cpython    conda-forge
python_abi                3.8                      1_cp38    conda-forge
qt                        5.12.5               hd8c4c69_1    conda-forge
readline                  8.0                  hf8c457e_0    conda-forge
scipy                     1.4.1            py38h18bccfc_3    conda-forge
setuptools                46.1.3           py38h32f6830_0    conda-forge
six                       1.14.0                     py_1    conda-forge
sqlite                    3.30.1               hcee41ef_0    conda-forge
tk                        8.6.10               hed695b0_0    conda-forge
wheel                     0.34.2                     py_1    conda-forge
xorg-kbproto              1.0.7             h14c3975_1002    conda-forge
xorg-libice               1.0.10               h516909a_0    conda-forge
xorg-libsm                1.2.3             h84519dc_1000    conda-forge
xorg-libx11               1.6.9                h516909a_0    conda-forge
xorg-libxau               1.0.9                h14c3975_0    conda-forge
xorg-libxdmcp             1.1.3                h516909a_0    conda-forge
xorg-libxext              1.3.4                h516909a_0    conda-forge
xorg-libxrender           0.9.10            h516909a_1002    conda-forge
xorg-renderproto          0.11.1            h14c3975_1002    conda-forge
xorg-xextproto            7.3.0             h14c3975_1002    conda-forge
xorg-xproto               7.0.31            h14c3975_1007    conda-forge
xz                        5.2.5                h516909a_0    conda-forge
zlib                      1.2.11            h516909a_1006    conda-forge
```

**Comment by davve2** [comment]
@standage   I´m looking into this issue. It would be great to get some more details about your operating system and installed packages similar to what Caroline posted above. I cannot replicate your problem using default installations in conda.

**Comment by standage** [comment]
Sorry for the delayed response, I am trying to catch up after a 3-day holiday weekend.

I am using CentOS 7 and Conda 4.8.3. See my setup below.

I have tried several configurations and methods of installing CanSNPer2 and ETE3 beside what is shown below, but I continue to have issues. I have found some of the issue threads mentioned above, but I confirmed from the Python interpreter that PyQt5 is installed correctly.

```
(base) [standage@worky ~]$ cat /etc/redhat-release
CentOS Linux release 7.7.1908 (Core)
(base) [standage@worky ~]$ cat ~/.condarc
channels:
  - etetoolkit
  - bioconda
  - conda-forge
  - defaults
(base) [standage@worky ~]$ conda create --name cansnper2 -y cansnper2
Collecting package metadata (current_repodata.json): done
Solving environment: done

## Package Plan ##

  environment location: /home/standage/anaconda3/envs/cansnper2

  added / updated specs:
    - cansnper2


The following NEW packages will be INSTALLED:

  _libgcc_mutex      conda-forge/linux-64::_libgcc_mutex-0.1-conda_forge
  _openmp_mutex      conda-forge/linux-64::_openmp_mutex-4.5-1_llvm
  binutils_impl_lin~ conda-forge/linux-64::binutils_impl_linux-64-2.34-h53a641e_2
  ca-certificates    conda-forge/linux-64::ca-certificates-2020.4.5.1-hecc5488_0
  cansnper2          bioconda/noarch::cansnper2-2.0.6-py_0
  certifi            conda-forge/linux-64::certifi-2020.4.5.1-py38h32f6830_0
  dbus               conda-forge/linux-64::dbus-1.13.6-he372182_0
  ete3               etetoolkit/noarch::ete3-3.1.1-pyhf5214e1_0
  expat              conda-forge/linux-64::expat-2.2.9-he1b5a44_2
  flextaxd           bioconda/noarch::flextaxd-0.2.1-py_0
  fontconfig         conda-forge/linux-64::fontconfig-2.13.1-h86ecdb6_1001
  freetype           conda-forge/linux-64::freetype-2.10.2-he06d7ca_0
  gcc_impl_linux-64  conda-forge/linux-64::gcc_impl_linux-64-7.5.0-hd420e75_6
  gettext            conda-forge/linux-64::gettext-0.19.8.1-hc5be6a0_1002
  gfortran_impl_lin~ conda-forge/linux-64::gfortran_impl_linux-64-7.5.0-hdf63c60_6
  glib               conda-forge/linux-64::glib-2.64.3-h6f030ca_0
  gst-plugins-base   conda-forge/linux-64::gst-plugins-base-1.14.5-h0935bb2_2
  gstreamer          conda-forge/linux-64::gstreamer-1.14.5-h36ae1b5_2
  gxx_impl_linux-64  conda-forge/linux-64::gxx_impl_linux-64-7.5.0-hdf63c60_6
  icu                conda-forge/linux-64::icu-64.2-he1b5a44_1
  jpeg               conda-forge/linux-64::jpeg-9c-h14c3975_1001
  ld_impl_linux-64   conda-forge/linux-64::ld_impl_linux-64-2.34-h53a641e_2
  libblas            conda-forge/linux-64::libblas-3.8.0-16_openblas
  libcblas           conda-forge/linux-64::libcblas-3.8.0-16_openblas
  libclang           conda-forge/linux-64::libclang-9.0.1-default_hde54327_0
  libffi             conda-forge/linux-64::libffi-3.2.1-he1b5a44_1007
  libgcc-ng          conda-forge/linux-64::libgcc-ng-9.2.0-h24d8f2e_2
  libgfortran-ng     conda-forge/linux-64::libgfortran-ng-7.5.0-hdf63c60_6
  libgomp            conda-forge/linux-64::libgomp-9.2.0-h24d8f2e_2
  libiconv           conda-forge/linux-64::libiconv-1.15-h516909a_1006
  liblapack          conda-forge/linux-64::liblapack-3.8.0-16_openblas
  libllvm9           conda-forge/linux-64::libllvm9-9.0.1-he513fc3_1
  libopenblas        conda-forge/linux-64::libopenblas-0.3.9-h5ec1e0e_0
  libpng             conda-forge/linux-64::libpng-1.6.37-hed695b0_1
  libstdcxx-ng       conda-forge/linux-64::libstdcxx-ng-9.2.0-hdf63c60_2
  libuuid            conda-forge/linux-64::libuuid-2.32.1-h14c3975_1000
  libxcb             conda-forge/linux-64::libxcb-1.13-h14c3975_1002
  libxkbcommon       conda-forge/linux-64::libxkbcommon-0.10.0-he1b5a44_0
  libxml2            conda-forge/linux-64::libxml2-2.9.10-hee79883_0
  libxslt            conda-forge/linux-64::libxslt-1.1.33-h31b3aaa_0
  llvm-openmp        conda-forge/linux-64::llvm-openmp-10.0.0-hc9558a2_0
  lxml               conda-forge/linux-64::lxml-4.5.1-py38hbb43d70_0
  ncurses            conda-forge/linux-64::ncurses-6.1-hf484d3e_1002
  nspr               conda-forge/linux-64::nspr-4.25-he1b5a44_0
  nss                conda-forge/linux-64::nss-3.47-he751ad9_0
  numpy              conda-forge/linux-64::numpy-1.18.4-py38h8854b6b_0
  openssl            conda-forge/linux-64::openssl-1.1.1g-h516909a_0
  pcre               conda-forge/linux-64::pcre-8.44-he1b5a44_0
  pip                conda-forge/noarch::pip-20.1.1-pyh9f0ad1d_0
  progressivemauve   bioconda/linux-64::progressivemauve-snapshot_2015_02_13-2
  pthread-stubs      conda-forge/linux-64::pthread-stubs-0.4-h14c3975_1001
  pyqt               conda-forge/linux-64::pyqt-5.12.3-py38ha8c2ead_3
  python             conda-forge/linux-64::python-3.8.2-he5300dc_7_cpython
  python_abi         conda-forge/linux-64::python_abi-3.8-1_cp38
  qt                 conda-forge/linux-64::qt-5.12.5-hd8c4c69_1
  readline           conda-forge/linux-64::readline-8.0-hf8c457e_0
  scipy              conda-forge/linux-64::scipy-1.4.1-py38h18bccfc_3
  setuptools         conda-forge/linux-64::setuptools-46.4.0-py38h32f6830_0
  six                conda-forge/noarch::six-1.15.0-pyh9f0ad1d_0
  sqlite             conda-forge/linux-64::sqlite-3.30.1-hcee41ef_0
  sysroot_linux-64   conda-forge/noarch::sysroot_linux-64-2.12-h3a0023d_3
  tk                 conda-forge/linux-64::tk-8.6.10-hed695b0_0
  wheel              conda-forge/noarch::wheel-0.34.2-py_1
  xorg-libxau        conda-forge/linux-64::xorg-libxau-1.0.9-h14c3975_0
  xorg-libxdmcp      conda-forge/linux-64::xorg-libxdmcp-1.1.3-h516909a_0
  xz                 conda-forge/linux-64::xz-5.2.5-h516909a_0
  zlib               conda-forge/linux-64::zlib-1.2.11-h516909a_1006


Preparing transaction: done
Verifying transaction: done
Executing transaction: done
#
# To activate this environment, use
#
#     $ conda activate cansnper2
#
# To deactivate an active environment, use
#
#     $ conda deactivate
(base) [standage@worky ~]$ conda activate cansnper2
(cansnper2) [standage@worky ~]$ conda list
# packages in environment at /home/standage/anaconda3/envs/cansnper2:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                      1_llvm    conda-forge
binutils_impl_linux-64    2.34                 h53a641e_2    conda-forge
ca-certificates           2020.4.5.1           hecc5488_0    conda-forge
cansnper2                 2.0.6                      py_0    bioconda
certifi                   2020.4.5.1       py38h32f6830_0    conda-forge
dbus                      1.13.6               he372182_0    conda-forge
ete3                      3.1.1              pyhf5214e1_0    etetoolkit
expat                     2.2.9                he1b5a44_2    conda-forge
flextaxd                  0.2.1                      py_0    bioconda
fontconfig                2.13.1            h86ecdb6_1001    conda-forge
freetype                  2.10.2               he06d7ca_0    conda-forge
gcc_impl_linux-64         7.5.0                hd420e75_6    conda-forge
gettext                   0.19.8.1          hc5be6a0_1002    conda-forge
gfortran_impl_linux-64    7.5.0                hdf63c60_6    conda-forge
glib                      2.64.3               h6f030ca_0    conda-forge
gst-plugins-base          1.14.5               h0935bb2_2    conda-forge
gstreamer                 1.14.5               h36ae1b5_2    conda-forge
gxx_impl_linux-64         7.5.0                hdf63c60_6    conda-forge
icu                       64.2                 he1b5a44_1    conda-forge
jpeg                      9c                h14c3975_1001    conda-forge
ld_impl_linux-64          2.34                 h53a641e_2    conda-forge
libblas                   3.8.0               16_openblas    conda-forge
libcblas                  3.8.0               16_openblas    conda-forge
libclang                  9.0.1           default_hde54327_0    conda-forge
libffi                    3.2.1             he1b5a44_1007    conda-forge
libgcc-ng                 9.2.0                h24d8f2e_2    conda-forge
libgfortran-ng            7.5.0                hdf63c60_6    conda-forge
libgomp                   9.2.0                h24d8f2e_2    conda-forge
libiconv                  1.15              h516909a_1006    conda-forge
liblapack                 3.8.0               16_openblas    conda-forge
libllvm9                  9.0.1                he513fc3_1    conda-forge
libopenblas               0.3.9                h5ec1e0e_0    conda-forge
libpng                    1.6.37               hed695b0_1    conda-forge
libstdcxx-ng              9.2.0                hdf63c60_2    conda-forge
libuuid                   2.32.1            h14c3975_1000    conda-forge
libxcb                    1.13              h14c3975_1002    conda-forge
libxkbcommon              0.10.0               he1b5a44_0    conda-forge
libxml2                   2.9.10               hee79883_0    conda-forge
libxslt                   1.1.33               h31b3aaa_0    conda-forge
llvm-openmp               10.0.0               hc9558a2_0    conda-forge
lxml                      4.5.1            py38hbb43d70_0    conda-forge
ncurses                   6.1               hf484d3e_1002    conda-forge
nspr                      4.25                 he1b5a44_0    conda-forge
nss                       3.47                 he751ad9_0    conda-forge
numpy                     1.18.4           py38h8854b6b_0    conda-forge
openssl                   1.1.1g               h516909a_0    conda-forge
pcre                      8.44                 he1b5a44_0    conda-forge
pip                       20.1.1             pyh9f0ad1d_0    conda-forge
progressivemauve          snapshot_2015_02_13               2    bioconda
pthread-stubs             0.4               h14c3975_1001    conda-forge
pyqt                      5.12.3           py38ha8c2ead_3    conda-forge
pyqt5-sip                 4.19.18                  pypi_0    pypi
pyqtchart                 5.12                     pypi_0    pypi
pyqtwebengine             5.12.1                   pypi_0    pypi
python                    3.8.2           he5300dc_7_cpython    conda-forge
python_abi                3.8                      1_cp38    conda-forge
qt                        5.12.5               hd8c4c69_1    conda-forge
readline                  8.0                  hf8c457e_0    conda-forge
scipy                     1.4.1            py38h18bccfc_3    conda-forge
setuptools                46.4.0           py38h32f6830_0    conda-forge
six                       1.15.0             pyh9f0ad1d_0    conda-forge
sqlite                    3.30.1               hcee41ef_0    conda-forge
sysroot_linux-64          2.12                 h3a0023d_3    conda-forge
tk                        8.6.10               hed695b0_0    conda-forge
wheel                     0.34.2                     py_1    conda-forge
xorg-libxau               1.0.9                h14c3975_0    conda-forge
xorg-libxdmcp             1.1.3                h516909a_0    conda-forge
xz                        5.2.5                h516909a_0    conda-forge
zlib                      1.2.11            h516909a_1006    conda-forge
```

**Comment by standage** [comment]
If I run the same step without the `etetoolkit` in my `~/.condarc`, it installs Python 3.6 instead of Python 3.8 but I still get the same runtime error with `ete3.NodeStyle()`.

**Comment by davve2** [comment]
Thank you @standage 

I am trying to recreate your bug, would it be possible for you to try ete3 directly in python to see if we can pinpoint the problem.

What happens if you run the command ete3.NodeStyle() in a python terminal after importing ete3?

python
Python 3.8.2 | packaged by conda-forge | (default, Mar  5 2020, 17:11:00)
[GCC 7.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import ete3
>>> ete3.NodeStyle()
{'fgcolor': '#0030c1', 'bgcolor': '#FFFFFF', 'vt_line_color': '#000000', 'hz_line_color': '#000000', 'hz_line_type': 0, 'vt_line_type': 0, 'size': 3, 'shape': 'circle', 'draw_descendants': True, 'hz_line_width': 0, 'vt_line_width': 0}

If that is still giving you an error try instead: (which is how it is solved in CanSNPer)
>>> from ete3 import NodeStyle
>>> NodeStyle()
{'fgcolor': '#0030c1', 'bgcolor': '#FFFFFF', 'vt_line_color': '#000000', 'hz_line_color': '#000000', 'hz_line_type': 0, 'vt_line_type': 0, 'size': 3, 'shape': 'circle', 'draw_descendants': True, 'hz_line_width': 0, 'vt_line_width': 0}

**Comment by druvus** [comment]
Seems you have the old channel order. Bioconda changed this last year to be dependent on conda-forge. Please follow the instructions here to correct it: https://bioconda.github.io/user/install.html#set-up-channels

**Comment by standage** [comment]
I fixed the channel order, but I'm getting the same result.

```
$ python
Python 3.8.2 | packaged by conda-forge | (default, Apr 24 2020, 08:20:52) 
[GCC 7.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from ete3 import NodeStyle
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name 'NodeStyle' from 'ete3' (/home/standage/anaconda3/envs/cansnper2/lib/python3.8/site-packages/ete3/__init__.py)
>>> import ete3
>>> ete3.NodeStyle()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'ete3' has no attribute 'NodeStyle'
```

**Comment by standage** [comment]
Hello again! I've been digging through this again, but unable to find root cause. Any luck on your end?
